import { Zap, Brush, Sparkles, Wind, Trees as Tree, Droplets, BookOpen, Key, Music, Flower2 } from 'lucide-react';

export const experienceCategories = [
  {
    id: 'soin_energetique',
    title: 'Soin & Activation Énergétique',
    icon: Zap,
    subcategories: [
      { id: 'massage_intuitif', label: 'Massage intuitif' },
      { id: 'realignement_pilier_lumiere', label: 'Réalignement pilier de lumière' },
      { id: 'harmonisation_energetique', label: 'Harmonisation énergétique' },
      { id: 'soin_sonore', label: 'Soin sonore / sonothérapie' },
      { id: 'bain_argile_plantes', label: 'Bain d’argile ou aux plantes' },
      { id: 'activation_chakras', label: 'Activation des chakras' },
    ],
  },
  {
    id: 'creation_ame',
    title: 'Création & Expression d’Âme',
    icon: Brush,
    subcategories: [
      { id: 'peinture_vibratoire', label: 'Peinture vibratoire' },
      { id: 'sculpture_intuitive', label: 'Sculpture intuitive' },
      { id: 'fabrication_talisman', label: 'Fabrication de talisman' },
      { id: 'artisanat_sacre', label: 'Artisanat sacré' },
      { id: 'ecriture_inspiree', label: 'Écriture inspirée' },
      { id: 'mandalas_fresques', label: 'Mandalas ou fresques collectives' },
    ],
  },
  {
    id: 'meditation_rituels',
    title: 'Méditation & Rituels Sacrés',
    icon: Sparkles,
    subcategories: [
      { id: 'meditation_guidee', label: 'Méditation guidée' },
      { id: 'ceremonie_cacao', label: 'Cérémonie du cacao' },
      { id: 'rituel_passage', label: 'Rituel de passage' },
      { id: 'cercle_lune', label: 'Cercle de lune' },
      { id: 'invocation_elements', label: 'Invocation des éléments' },
      { id: 'prieres_chants', label: 'Prières ou chants sacrés' },
    ],
  },
  {
    id: 'voyage_sensoriel',
    title: 'Voyage Sensoriel & Immersion',
    icon: Wind,
    subcategories: [
      { id: 'bain_sonore_sensoriel', label: 'Bain sonore' },
      { id: 'voyage_olfactif', label: 'Voyage olfactif' },
      { id: 'experience_multisensorielle', label: 'Expérience multi-sensorielle' },
      { id: 'visualisation_creatrice', label: 'Visualisation créatrice' },
      { id: 'rituel_5_sens', label: 'Rituel aux 5 sens' },
      { id: 'parcours_immersif_lumiere', label: 'Parcours immersif en lumière' },
    ],
  },
  {
    id: 'connexion_nature',
    title: 'Connexion & Offrandes à la Nature',
    icon: Tree,
    subcategories: [
      { id: 'marche_consciente', label: 'Marche consciente' },
      { id: 'ceremonie_feu_eau', label: 'Cérémonie au feu ou à l’eau' },
      { id: 'plantation_soin_arbre', label: 'Plantation ou soin à un arbre' },
      { id: 'rituel_foret_mer', label: 'Rituel en forêt ou en bord de mer' },
      { id: 'alliance_element', label: 'Alliance avec un élément' },
      { id: 'observation_ciel_astres', label: 'Observation sacrée du ciel et des astres' },
    ],
  },
  {
    id: 'nettoyage_purification',
    title: 'Nettoyage & Purification',
    icon: Droplets,
    subcategories: [
      { id: 'bain_detox_plantes', label: 'Bain détox aux plantes' },
      { id: 'rituel_fumigation', label: 'Rituel de fumigation' },
      { id: 'liberation_energetique', label: 'Libération énergétique' },
      { id: 'purification_argile', label: 'Purification par l’argile' },
      { id: 'reconnexion_eau', label: 'Reconnexion à l’eau' },
      { id: 'nettoyage_vibratoire', label: 'Nettoyage vibratoire des corps subtils' },
    ],
  },
  {
    id: 'histoires_sagesses',
    title: 'Histoires & Sagesses Ancestrales',
    icon: BookOpen,
    subcategories: [
      { id: 'cercle_conte', label: 'Cercle de conte' },
      { id: 'enseignement_oral', label: 'Enseignement oral' },
      { id: 'transmission_culturelle', label: 'Transmission culturelle' },
      { id: 'mythe_legende_vivante', label: 'Mythe ou légende vivante' },
      { id: 'lecture_ame', label: 'Lecture d’âme' },
      { id: 'partage_traditions', label: 'Partage de traditions locales' },
    ],
  },
  {
    id: 'portes_conscience',
    title: 'Portes de Conscience',
    icon: Key,
    subcategories: [
      { id: 'initiation_spirituelle', label: 'Initiation spirituelle' },
      { id: 'exploration_invisible', label: 'Exploration de l’invisible' },
      { id: 'voyage_chamanique', label: 'Voyage chamanique' },
      { id: 'activation_chakras_superieurs', label: 'Activation de chakras supérieurs' },
      { id: 'expansion_perception', label: 'Expansion de perception' },
      { id: 'etats_modifies_conscience', label: 'États modifiés de conscience' },
    ],
  },
  {
    id: 'danses_songes',
    title: 'Danses & Songes Libérateurs',
    icon: Music,
    subcategories: [
      { id: 'danse_intuitive', label: 'Danse intuitive' },
      { id: 'mouvement_libre', label: 'Mouvement libre' },
      { id: 'transe_sacree', label: 'Transe sacrée' },
      { id: 'reve_eveille', label: 'Rêve éveillé' },
      { id: 'yoga_danse', label: 'Yoga dansé' },
      { id: 'danse_medecine', label: 'Danse médecine' },
    ],
  },
  {
    id: 'couronne_lumiere',
    title: 'Couronne de Lumière',
    icon: Flower2,
    subcategories: [
      { id: 'coiffure_energetique', label: 'Coiffure énergétique' },
      { id: 'benediction_tete', label: 'Bénédiction de la tête' },
      { id: 'ornement_sacre', label: 'Ornement sacré' },
      { id: 'activation_couronne', label: 'Activation du chakra couronne' },
      { id: 'massage_cranien_vibratoire', label: 'Massage crânien vibratoire' },
      { id: 'couronne_florale_minerale', label: 'Couronne florale ou minérale' },
    ],
  },
];